server:
  port: 7902
  servlet:
    context-path: /msgoods
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    # seSSL=false,避免安全检查
    url: jdbc:mysql://192.168.1.12/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    # 控制台是否打印原生SQL语句
    show-sql: true
  application:
    name: microservice-provider-goods
logging:
  pattern:
    console: "%d - %msg%n"
    level:
      com.baihoomuch.cloud: info
  path: G:/IntelliJ_IDEALog/IDEA_Microservice/microservices-pring-cloud
  file: G:/IntelliJ_IDEALog/IDEA_Microservice/microservices-pring-cloud/microserviceGoods.log
eureka:
  client:
    service-url:
      #eureka默认铺设到指定 URL 上
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    # 默認是 false，是否啓動IP訪問
    prefer-ip-address: true
    # 改配置相當與 IP地址:我的應用名稱:端口
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      